/* GIO - GLib Input, Output and Streaming Library
 *
 * Copyright (C) 2022-2025 Sergey Bugaev
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include "config.h"

#include "ghurdfilemonitor.h"
#include "fs_notify_S.h"
#include <gio/giomodule.h>
#include "glibintl.h"

#include <hurd.h>

/* GHurdFileMonitor is a GLocalFileMonitor implementation for GNU/Hurd,
 * implemented on top of the Hurd's file and directory change
 * notification mechanism (see <hurd/fs_notify.defs> in the Hurd source
 * tree).
 *
 * To receive notifications, we look up a file or directory port, and
 * ask it to notify us of any changes by using the
 * file_notice_changes () or dir_notice_changes () RPCs.  We provide a
 * port that we want to receive change notifications on, for which we
 * hold a receive right.
 *
 * Since listening for arbitrary incoming Mach messages can't be easily
 * integrated into glib's fd-based main loop, we spawn a separate worker
 * thread to listen for incoming change notifications.  The thread runs
 * the standard Mach message server loop, as implemented by glibc's
 * mach_msg_server () function.
 *
 * Each GHurdFileMonitor instance contains (up to) two Mach ports on
 * which it listens on; for file and directory change notifications.  We
 * use two separate ports rather than using a single port for both in
 * order to be able to unsubscribe from file change notifications easily
 * by destroying and (if needed) recreating one of the ports, without it
 * interfering with directory change notifications.  All of the ports of
 * all GHurdFileMonitor instances are placed into a single port set, on
 * which the worker thread receives messages from.
 *
 * When a change happens to a file or directory that we are watching,
 * the translator (file system implementation) sends us a Mach message
 * representing a file_changed () or a dir_changed () RPC.  Upon
 * receiving the message, the worker thread calls into the
 * fs_notify_server () "demuxer" function, whose code is generated by
 * MIG, the Mach Interface Generator (see fs_notifyServer.c in the build
 * tree).  If the message is confirmed to be a valid file_changed () RPC
 * invocation, the MIG-generated code looks up the GHurdFileMonitor
 * corresponding to the Mach port the message has arrived on, and
 * invokes the S_file_changed () function defined in this file.  The
 * relevant part of the code looks like this (simplified, see
 * fs_notifyServer.c for the full picture):
 *
 *   GHurdFileMonitor *monitor =
 *     g_hurd_file_monitor_lookup_by_port (In0P->msgh_request_port);
 *
 *   OutP->RetCode = S_file_changed (monitor,
 *                                   In0P->tickno, In0P->change,
 *                                   In0P->start, In0P->end);
 *   g_hurd_file_monitor_unref0 (monitor);
 *
 * where In0P is the received notification message, and OutP is the
 * would-be response message, except that there's none, because both
 * file_changed () and dir_changed () are "simple routines" that don't
 * have a response message.
 *
 * It is the fs_notify.defs file in this directory that directs MIG to
 * generate the g_hurd_file_monitor_lookup_by_port () and
 * g_hurd_file_monitor_unref0 () function calls, and then includes
 * <hurd/fs_notify.defs>.
 *
 * The code here doesn't attempt to handle errors like failure to
 * allocate a port, since if we cannot allocate a port, we've got much
 * more serious issues, and since neither do glibc and the rest of the
 * Hurd.  However, an attempt is made to handle a translator not
 * supporting the change notifications mechanism, which some translators
 * indeed don't.  In this case, g_hurd_file_monitor_start () returns an
 * error, and g_file_monitor_file () falls back to polling.
 *
 */

struct _GHurdFileMonitor
{
  GLocalFileMonitor parent_instance;

  file_t directory;
  gchar *basename;

  /* The ports we receive change notifications on.  */
  mach_port_t dir_notify_port;
  mach_port_t file_notify_port;
  gboolean watch_hard_links : 1;
};

G_DEFINE_TYPE_WITH_CODE (GHurdFileMonitor, g_hurd_file_monitor, G_TYPE_LOCAL_FILE_MONITOR,
                         g_io_extension_point_implement (G_LOCAL_FILE_MONITOR_EXTENSION_POINT_NAME,
                                                         g_define_type_id, "hurd", 20))


static mach_port_t notify_port_set;
static GRecMutex worker_lock;
/* Hash table mapping notify port names back to their GHurdFileMonitor
 * pointers.
 */
static GHashTable *monitor_hash_table;  /* (element-type guint GHurdFileMonitor) (mutex worker_lock) */

/*
 * g_hurd_file_monitor_lookup_by_port:
 * @port: (transfer none): a Mach port of a [class@Gio.HurdFileMonitor].
 *
 * Look up a [class@Gio.HurdFileMonitor] by one of its two ports.  This
 * is used by the MIG-generated server code to dispatch incoming Mach
 * messages.
 *
 * Returns: (transfer full) (nullable): The monitor referenced by the port.
 */
GHurdFileMonitor *
g_hurd_file_monitor_lookup_by_port (mach_port_t port)
{
  GHurdFileMonitor *monitor;

  g_return_val_if_fail (MACH_PORT_VALID (port), NULL);

  g_rec_mutex_lock (&worker_lock);
  monitor = g_hash_table_lookup (monitor_hash_table,
                                 GUINT_TO_POINTER (port));
  /* Reference the monitor before releasing the lock.
   *
   * Note: this can be NULL if the monitor is being torn down and has
   * already been removed from the hash table while its port right is
   * either still alive or has just been destroyed, but the other
   * thread is still processing a previously received message directed
   * to it.  That, or the port doesn't refer to a monitor in the first
   * place.
   */
  if G_LIKELY (monitor)
    g_object_ref (monitor);

  g_rec_mutex_unlock (&worker_lock);

  return monitor;
}

/*
 * g_hurd_file_monitor_lookup_by_payload:
 * @payload: Protected payload received in a message.
 *
 * This function would be called by the MIG-generated server code if it
 * was to receive a Mach message with a protected payload, but we never
 * set protected payloads on [class@Gio.HurdFileMonitor] ports, since
 * there are unfortunate complications with racing during monitor
 * destruction.
 *
 * Returns: (transfer full) (not nullable): The looked up monitor.
 */
GHurdFileMonitor *
g_hurd_file_monitor_lookup_by_payload (uintptr_t payload)
{
#if 0
  GHurdFileMonitor *monitor = G_HURD_FILE_MONITOR (payload);
  return g_object_ref (monitor);
#else
  g_assert_not_reached ();
#endif
}

/*
 * g_hurd_file_monitor_unref0:
 * @monitor: (nullable) (transfer full): A monitor
 *
 * Release the #GHurdFileMonitor reference obtained with
 * [func@Gio.HurdFileMonitor.lookup_by_port] or
 * [func@Gio.HurdFileMonitor.lookup_by_payload].
 */
void
g_hurd_file_monitor_unref0 (GHurdFileMonitor *monitor)
{
  if (!monitor)
    return;
  g_object_unref (monitor);
}

static gpointer
worker_thread (gpointer user_data)
{
  /* The worker thread runs the Mach message server loop.  This will
   * result in instances of GHurdFileMonitor being looked up using the two
   * functions defined above, as well as the in the S_ callbacks, defined
   * below, being invoked.
   */
  mach_msg_server (fs_notify_server, 0, notify_port_set);
  return NULL;
}

/* Initialize the Mach port set, the hash table and the worker thread.  */
static gpointer
do_init_worker (gpointer user_data)
{
  error_t err;

  /* Don't attempt to handle failure here, because if port allocation
   * fails then this whole process has bigger problems.  */
  err = mach_port_allocate (mach_task_self (), MACH_PORT_RIGHT_PORT_SET,
                            &notify_port_set);
  g_assert (!err);

  monitor_hash_table = g_hash_table_new (g_direct_hash, g_direct_equal);

  g_thread_new ("ghurdfilemonitor", worker_thread, NULL);
  return NULL;
}

/**
 * g_hurd_file_monitor_ensure_port:
 * @monitor: A monitor
 * @port: (inout) (transfer full) (not optional):
 */
static void
g_hurd_file_monitor_ensure_port (GHurdFileMonitor *monitor,
                                 mach_port_t      *port)
{
  error_t err;
  gboolean newly_added;

  /* If the port is already valid, we have nothing to do.  */
  if (*port != MACH_PORT_NULL)
    return;

  /* Allocate a new Mach port.  */
  err = mach_port_allocate (mach_task_self (),
                            MACH_PORT_RIGHT_RECEIVE,
                            port);
  g_assert (!err);

  /* Make sure to init the hashtable and the port we use below.  */
  static GOnce init_worker_once = G_ONCE_INIT;
  g_once (&init_worker_once, do_init_worker, NULL);

  /* Place the port+monitor pair into the hash table, so the monitor
   * can be looked up in g_hurd_file_monitor_lookup_by_port ().
   */
  g_rec_mutex_lock (&worker_lock);
  newly_added = g_hash_table_insert (monitor_hash_table,
                                     GUINT_TO_POINTER (*port),
                                     monitor);
  g_rec_mutex_unlock (&worker_lock);
  g_assert (newly_added);

  /* Finally, add the port to the port set the worker thread listens
   * for incoming messages on.
   */
  err = mach_port_move_member (mach_task_self (), *port,
                               notify_port_set);
  g_assert (!err);
}

/**
 * g_hurd_file_monitor_destroy_port:
 * @monitor: A monitor
 * @port: (inout) (transfer full) (not optional): A port right to destroy
 */
static void
g_hurd_file_monitor_destroy_port (GHurdFileMonitor *monitor,
                                  mach_port_t      *port)
{
  error_t err;
  gboolean found;

  /* If there's no port, we have nothing to do.  */
  if (*port == MACH_PORT_NULL)
    return;

  g_rec_mutex_lock (&worker_lock);
  found = g_hash_table_remove (monitor_hash_table,
                               GUINT_TO_POINTER (*port));
  g_rec_mutex_unlock (&worker_lock);
  g_assert (found);

  /* Destroy the receive right.  */
  err = mach_port_mod_refs (mach_task_self (), *port,
                            MACH_PORT_RIGHT_RECEIVE, -1);
  g_assert (!err);

  *port = MACH_PORT_NULL;
}

static gboolean
g_hurd_file_monitor_is_supported (void)
{
  /*
   * Check if this file monitoring mechanism is supported at all.
   * Since we're on a GNU/Hurd system, fs_notify-based file monitoring
   * is supported in general.  We can't check whether an individual
   * translator / filesystem node supports it here, since we can't
   * know which translator we're going to be used with.  So if a
   * translator does not support fs_notify, we'll report this as
   * an error when a GHurdFileMonitor instance is started.
   */
  return TRUE;
}

static gboolean
g_hurd_file_monitor_watch_directory (GHurdFileMonitor *monitor,
                                     const gchar      *path,
                                     GError          **error)
{
  error_t err;
  file_t dir;

  g_assert (monitor->directory == MACH_PORT_NULL);

  dir = monitor->directory = file_name_lookup (path, O_NORW | O_DIRECTORY, 0);

  /* Did that work? */
  if (!MACH_PORT_VALID (dir))
    {
      err = errno;

      if G_UNLIKELY (dir == MACH_PORT_DEAD)
        {
          err = EIEIO;
          monitor->directory = MACH_PORT_NULL;
        }

      g_set_error (error, G_IO_ERROR, g_io_error_from_errno (err),
                   _("Could not look up directory ‘%s’ for watching: %s"),
                   path, g_strerror (err));
      return FALSE;
    }

  /* Ask the directory to notify us of any changes.  */
  g_hurd_file_monitor_ensure_port (monitor, &monitor->dir_notify_port);
  err = dir_notice_changes (dir, monitor->dir_notify_port,
                            MACH_MSG_TYPE_MAKE_SEND);
  switch (err)
    {
    case 0:
      /* It worked! */
      return TRUE;

    case EOPNOTSUPP:
    case EMIG_BAD_ID:
      /* This file system does not support actively notifying its
       * clients of changes.  Communicate that to our caller, so it
       * can fall back onto polling.
       */
      g_set_error (error, G_IO_ERROR, G_IO_ERROR_NOT_SUPPORTED,
                   _("File system containing ‘%s’ doesn’t support change notifications"),
                   path);
      break;

    default:
      /* Something else went wrong.  */
      g_set_error (error, G_IO_ERROR, g_io_error_from_errno (err),
                   _("Could not watch directory ‘%s’: %s"),
                   path, g_strerror (err));
      break;
    }

  /* Since the above did not work, clean up the directory port now.  */
  err = mach_port_deallocate (mach_task_self (), dir);
  g_assert (!err);
  monitor->directory = MACH_PORT_NULL;

  return FALSE;
}


static gboolean
g_hurd_file_monitor_watch_file (GHurdFileMonitor *monitor,
                                GError          **error)
{
  error_t err, err2;
  file_t file;

  g_assert (monitor->basename);
  g_assert (MACH_PORT_VALID (monitor->directory));

  /* Note that we only have a basename of the file at this point, so we
   * use that in the error messages below instead of a full path.
   */

  file = file_name_lookup_under (monitor->directory,
                                 monitor->basename,
                                 O_NORW | O_NOLINK, 0);

  /* Did that work? */
  if (!MACH_PORT_VALID (file))
    {
      err = errno;

      if G_UNLIKELY (file == MACH_PORT_DEAD)
        err = EIEIO;

      if (err == ENOENT)
        /* This is not an error; the file does not currently exist.
         * We will start watching it when and if it appears.
         */
        return TRUE;

      g_set_error (error, G_IO_ERROR, g_io_error_from_errno (err),
                   _("Could not look up file ‘%s’ for watching: %s"),
                   monitor->basename, g_strerror (err));
      return FALSE;
    }

  /* Ask the file to notify us of any changes.  */
  g_hurd_file_monitor_ensure_port (monitor, &monitor->file_notify_port);
  err = file_notice_changes (file, monitor->file_notify_port,
                             MACH_MSG_TYPE_MAKE_SEND);
  /* In any case, deallocate the file port now.  */
  err2 = mach_port_deallocate (mach_task_self (), file);
  g_assert (!err2);

  switch (err)
    {
    case 0:
      /* It worked! */
      return TRUE;

    case EOPNOTSUPP:
    case EMIG_BAD_ID:
      /* This file system does not support actively notifying its
       * clients of changes.  Communicate that to our caller, so it
       * can fall back onto polling.
       */
      g_set_error (error, G_IO_ERROR, G_IO_ERROR_NOT_SUPPORTED,
                   _("File system containing ‘%s’ doesn’t support change notifications"),
                   monitor->basename);
      return FALSE;

    default:
      /* Something else went wrong.  */
      g_set_error (error, G_IO_ERROR, g_io_error_from_errno (err),
                   _("Could not watch file ‘%s’: %s"),
                   monitor->basename, g_strerror (err));
      return FALSE;
    }
}

static gboolean
g_hurd_file_monitor_start (GLocalFileMonitor  *local_monitor,
                           const gchar        *dirname,
                           const gchar        *basename,
                           const gchar        *filename,
                           GFileMonitorSource *source,
                           GError            **error)
{
  GHurdFileMonitor *hurd_monitor = G_HURD_FILE_MONITOR (local_monitor);
  gchar *dir_path;
  gboolean ok;

  g_clear_pointer (&hurd_monitor->basename, g_free);

  if (filename)
    {
      dir_path = g_path_get_dirname (filename);
      hurd_monitor->basename = g_path_get_basename (filename);
      hurd_monitor->watch_hard_links = TRUE;
    }
  else
    {
      dir_path = g_strdup (dirname);
      hurd_monitor->basename = g_strdup (basename);
    }

  ok = g_hurd_file_monitor_watch_directory (hurd_monitor, dir_path, error);
  g_free (dir_path);
  if (!ok)
    return FALSE;

  if (basename)
    {
      ok = g_hurd_file_monitor_watch_file (hurd_monitor, error);
      if (!ok)
        {
          g_hurd_file_monitor_destroy_port (hurd_monitor,
                                            &hurd_monitor->dir_notify_port);
          return FALSE;
        }
    }

  return TRUE;
}

static gboolean
g_hurd_file_monitor_cancel (GFileMonitor *monitor)
{
  GHurdFileMonitor *hurd_monitor = G_HURD_FILE_MONITOR (monitor);

  /* Stop listening for messages by destroying
     the ports we listen on.  */
  g_hurd_file_monitor_destroy_port (hurd_monitor,
                                    &hurd_monitor->file_notify_port);
  g_hurd_file_monitor_destroy_port (hurd_monitor,
                                    &hurd_monitor->dir_notify_port);

  return TRUE;
}

static void
g_hurd_file_monitor_finalize (GObject *object)
{
  error_t err;
  GHurdFileMonitor *hurd_monitor = G_HURD_FILE_MONITOR (object);

  if (MACH_PORT_VALID (hurd_monitor->directory))
    {
      err = mach_port_deallocate (mach_task_self (),
                                  hurd_monitor->directory);
      g_assert (!err);
    }
  g_clear_pointer (&hurd_monitor->basename, g_free);

  /* We must have been cancelled by this point.  */
  g_assert (hurd_monitor->file_notify_port == MACH_PORT_NULL);
  g_assert (hurd_monitor->dir_notify_port == MACH_PORT_NULL);

  G_OBJECT_CLASS (g_hurd_file_monitor_parent_class)->finalize (object);
}

static void
g_hurd_file_monitor_init (GHurdFileMonitor *monitor)
{
}

static void
g_hurd_file_monitor_class_init (GHurdFileMonitorClass *klass)
{
  GObjectClass *object_class = G_OBJECT_CLASS (klass);
  GFileMonitorClass *file_monitor_class = G_FILE_MONITOR_CLASS (klass);
  GLocalFileMonitorClass *local_file_monitor_class = G_LOCAL_FILE_MONITOR_CLASS (klass);

  object_class->finalize = g_hurd_file_monitor_finalize;

  local_file_monitor_class->start = g_hurd_file_monitor_start;
  local_file_monitor_class->is_supported = g_hurd_file_monitor_is_supported;
  file_monitor_class->cancel = g_hurd_file_monitor_cancel;
}

/* The two following callbacks are invoked from mach_msg_server ()
 * in the worker thread, when we get a notification Mach message.
 * Since both are simpleroutines, it doesn't actually matter which
 * error code they return.
 */

kern_return_t
S_dir_changed (GHurdFileMonitor *monitor, natural_t tickno,
               enum dir_changed_type change, const char *name)
{
  GFileMonitorEvent event_type;
  GSource *fms;
  GLocalFileMonitor *local_monitor = G_LOCAL_FILE_MONITOR (monitor);

  /* Reject messages on ports that don't correspond to valid file
   * monitors.
   */
  if G_UNLIKELY (monitor == NULL)
    return EOPNOTSUPP;

  /* Reject weird notifications.  */
  if G_UNLIKELY (!name || !name[0] || strchr (name, '/'))
    return EINVAL;

  /* When the directory itself is deleted, libdiskfs emits
   * DIR_CHANGED_UNLINK events for . and .., which GLocalFileMonitor
   * doesn't want to receive.  Filter them out.
   */
  if (!strcmp (name, ".") || !strcmp (name, ".."))
    return EGRATUITOUS;

  g_rec_mutex_lock (&worker_lock);

  /* If we only care about a specific basename, ignore all others.  */
  if (monitor->basename && strcmp (name, monitor->basename))
    {
      g_rec_mutex_unlock (&worker_lock);
      return EGRATUITOUS;
    }

  switch (change)
    {
    case DIR_CHANGED_NEW:
      // TODO: or G_FILE_MONITOR_EVENT_MOVED_IN?
      event_type = G_FILE_MONITOR_EVENT_CREATED;
      /* Our file did not exist previously, but it does now.  Start
       * watching it.  Ignore errors, since we don't have anywhere
       * to report them to.
       */
      if (monitor->basename)
        {
          g_hurd_file_monitor_destroy_port (monitor, &monitor->file_notify_port);
          g_hurd_file_monitor_watch_file (monitor, NULL);
        }
      break;

    case DIR_CHANGED_UNLINK:
      // TODO: or G_FILE_MONITOR_EVENT_MOVED_OUT?
      event_type = G_FILE_MONITOR_EVENT_DELETED;
      /* Our file went away, stop watching it.  */
      if (monitor->basename && !monitor->watch_hard_links)
        g_hurd_file_monitor_destroy_port (monitor, &monitor->file_notify_port);
      break;

    case DIR_CHANGED_RENUMBER:
      event_type = G_FILE_MONITOR_EVENT_CHANGED;
      /* Stop watching the old file, start watching the new file.  */
      if (monitor->basename)
        {
          g_hurd_file_monitor_destroy_port (monitor, &monitor->file_notify_port);
          g_hurd_file_monitor_watch_file (monitor, NULL);
        }
      break;

    default:
      g_rec_mutex_unlock (&worker_lock);
      return ENOTSUP;
    }

  fms = g_source_ref ((GSource *) local_monitor->source);
  g_rec_mutex_unlock (&worker_lock);
  g_file_monitor_source_handle_event ((GFileMonitorSource *) fms, event_type,
                                      name, NULL, NULL, g_get_monotonic_time ());
  g_source_unref (fms);
  return 0;
}

kern_return_t
S_file_changed (GHurdFileMonitor *monitor, natural_t tickno,
                enum file_changed_type change,
                loff_t start, loff_t end)
{
  GFileMonitorEvent event_type;
  GSource *fms;
  const char *basename;
  GLocalFileMonitor *local_monitor = G_LOCAL_FILE_MONITOR (monitor);

  /* Reject messages on ports that don't correspond to valid file
   * monitors.
   */
  if G_UNLIKELY (monitor == NULL)
    return EOPNOTSUPP;

  switch (change)
    {
    case FILE_CHANGED_WRITE:
    case FILE_CHANGED_EXTEND:
    case FILE_CHANGED_TRUNCATE:
      event_type = G_FILE_MONITOR_EVENT_CHANGED;
      break;

    case FILE_CHANGED_META:
      event_type = G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED;
      break;

    default:
      return ENOTSUP;
    }

  g_rec_mutex_lock (&worker_lock);
  fms = g_source_ref ((GSource *) local_monitor->source);
  basename = monitor->basename;
  g_rec_mutex_unlock (&worker_lock);

  g_file_monitor_source_handle_event ((GFileMonitorSource *) fms, event_type,
                                      basename, NULL, NULL, g_get_monotonic_time ());
  g_source_unref (fms);

  return 0;
}
