/* GIO - GLib Input, Output and Streaming Library
 *
 * Copyright 2026 Red Hat, Inc.
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include <glib/glib.h>
#include <glib/gstdio.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "gio.h"
#include "gmemorymonitorpsi.h"

typedef struct
{
  char *mock_psi_path;
  char *mock_proc_path;
  char *mock_write_env_path;
  char *mock_write_env_no_write;
} SetupData;

static void
tests_setup (SetupData *setup_data,
             gconstpointer data)
{
  char *proc_contents = NULL;
  GError *local_error = NULL;

  setup_data->mock_psi_path = g_build_filename (g_get_tmp_dir (), "cgroup", NULL);
  g_assert_no_errno (mkfifo (setup_data->mock_psi_path, S_IRUSR | S_IWUSR));

  setup_data->mock_proc_path = g_build_filename (g_get_tmp_dir (), "psi-proc", NULL);
  proc_contents = g_strdup_printf ("0::%s", setup_data->mock_psi_path);
  g_file_set_contents_full (setup_data->mock_proc_path, proc_contents,
                            -1, G_FILE_SET_CONTENTS_NONE,
                            S_IRUSR | S_IWUSR, &local_error);
  g_assert_no_error (local_error);
  g_clear_error (&local_error);

  setup_data->mock_write_env_path = g_build_filename (g_get_tmp_dir (), "write-env", NULL);
  g_file_set_contents_full (setup_data->mock_write_env_path, "",
                            -1, G_FILE_SET_CONTENTS_NONE,
                            S_IRUSR | S_IWUSR, &local_error);

  setup_data->mock_write_env_no_write = g_build_filename (g_get_tmp_dir (), "write-env-no-write", NULL);
  g_file_set_contents_full (setup_data->mock_write_env_no_write, "",
                            -1, G_FILE_SET_CONTENTS_NONE,
                            S_IRUSR | S_IWUSR, &local_error);

  g_free (proc_contents);
}

static void
tests_teardown (SetupData *setup_data,
                gconstpointer data)
{
  g_unlink (setup_data->mock_proc_path);
  g_free (setup_data->mock_proc_path);
  g_unlink (setup_data->mock_psi_path);
  g_free (setup_data->mock_psi_path);
  g_unlink (setup_data->mock_write_env_path);
  g_free (setup_data->mock_write_env_path);
  g_unlink (setup_data->mock_write_env_no_write);
  g_free (setup_data->mock_write_env_no_write);
}

static void
memory_monitor_psi_signal_cb (GMemoryMonitor *m,
                              GMemoryMonitorWarningLevel level,
                              gpointer user_data)
{
  int *out_warning_level = user_data;

  *out_warning_level = level;

  g_main_context_wakeup (NULL);
}

static void
test_receive_signals (SetupData *setup, gconstpointer data)
{
  GMemoryMonitorPsi *monitor;
  unsigned long warning_id;
  int warning_level = -1;
  GError *local_error = NULL;

  g_setenv ("MEMORY_PRESSURE_WATCH", setup->mock_psi_path, TRUE);
  g_setenv ("MEMORY_PRESSURE_WRITE", "c29tZSAxNTAwMDAgMTAwMDAwMA==", TRUE);

  g_file_set_contents (setup->mock_psi_path,
                       "some 150000 1000000",
                       -1,
                       &local_error);
  g_assert_no_error (local_error);

  monitor = g_object_new (G_TYPE_MEMORY_MONITOR_PSI,
                          "proc-path", setup->mock_proc_path,
                          NULL);
  warning_id = g_signal_connect (monitor, "low-memory-warning",
                                 G_CALLBACK (memory_monitor_psi_signal_cb), &warning_level);
  g_initable_init (G_INITABLE (monitor), NULL, &local_error);
  g_assert_no_error (local_error);

  while (warning_level == -1)
    g_main_context_iteration (NULL, TRUE);

  g_assert_true (warning_level == 50);

  g_signal_handler_disconnect (monitor, warning_id);
  g_object_unref (monitor);
}

static void
test_write_env (SetupData *setup, gconstpointer data)
{
  GMemoryMonitorPsi *monitor;
  unsigned long warning_id;
  int warning_level = -1;
  GError *local_error = NULL;
  gchar *read_data = NULL;
  gsize read_data_len = 0;
  gchar *base64_data = NULL;
  /* The contents is generated by running "dd if=/dev/random of=/foo/bar bs=128 count=1" */
  const gchar *env_write = "hVh9eV0BZsh/GWEs9V6zKyO3VUe2MnxTxLZbA7BRo7GJKHAAayIRsgO8EI4m8iFskhx/O4cAfpyL"
                           "YQ8LFHMG5XBuBmqD9spZghu0eVYF2X8lCCT+iBlEFw5dWiSa6XwJN++AmHi1tp4uJj0UBR7CwV5c"
                           "+ms9ZDUqOQrvlFHUSxw=";

  g_setenv ("MEMORY_PRESSURE_WATCH", setup->mock_write_env_path, TRUE);
  g_setenv ("MEMORY_PRESSURE_WRITE", env_write, TRUE);

  monitor = g_object_new (G_TYPE_MEMORY_MONITOR_PSI,
                          "proc-path", setup->mock_proc_path,
                          NULL);
  warning_id = g_signal_connect (monitor, "low-memory-warning",
                                 G_CALLBACK (memory_monitor_psi_signal_cb), &warning_level);
  g_initable_init (G_INITABLE (monitor), NULL, &local_error);
  g_assert_no_error (local_error);

  g_signal_handler_disconnect (monitor, warning_id);
  g_object_unref (monitor);

  /* Verify the write contents */
  g_file_get_contents (setup->mock_write_env_path, &read_data, &read_data_len, &local_error);
  g_assert_no_error (local_error);
  base64_data = g_base64_encode ((guchar *) read_data, read_data_len);
  g_assert_cmpstr (base64_data, ==, env_write);
  g_assert_cmpuint (read_data_len, ==, 128);
  g_free (read_data);
  g_free (base64_data);
  g_clear_error (&local_error);
}

static void
test_write_env_no_write (SetupData *setup, gconstpointer data)
{
  GMemoryMonitorPsi *monitor;
  unsigned long warning_id;
  int warning_level = -1;
  GError *local_error = NULL;
  gchar *read_data = NULL;
  gsize read_data_len = 0;
  gchar *base64_data = NULL;

  g_setenv ("MEMORY_PRESSURE_WATCH", setup->mock_write_env_no_write, TRUE);
  g_unsetenv ("MEMORY_PRESSURE_WRITE");

  monitor = g_object_new (G_TYPE_MEMORY_MONITOR_PSI,
                          "proc-path", setup->mock_proc_path,
                          NULL);
  warning_id = g_signal_connect (monitor, "low-memory-warning",
                                 G_CALLBACK (memory_monitor_psi_signal_cb), &warning_level);
  g_initable_init (G_INITABLE (monitor), NULL, &local_error);
  g_assert_no_error (local_error);

  g_signal_handler_disconnect (monitor, warning_id);
  g_object_unref (monitor);

  /* Verify the write contents */
  g_file_get_contents (setup->mock_write_env_no_write, &read_data, &read_data_len, &local_error);
  g_assert_no_error (local_error);
  base64_data = g_base64_encode ((guchar *) read_data, read_data_len);
  g_assert_cmpuint (read_data_len, ==, 0);
  g_free (read_data);
  g_free (base64_data);
  g_clear_error (&local_error);
}

int
main (int argc, char **argv)
{
  g_setenv ("GIO_USE_MEMORY_MONITOR", "psi", TRUE);

  g_test_init (&argc, &argv, G_TEST_OPTION_ISOLATE_DIRS, NULL);
  g_test_add ("/memory-monitor-psi-env-set/receive-signal", SetupData, NULL,
              tests_setup, test_receive_signals, tests_teardown);

  g_test_add ("/memory-monitor-psi-env-set/write-env-no-write", SetupData, NULL,
              tests_setup, test_write_env_no_write, tests_teardown);

  g_test_add ("/memory-monitor-psi-env-set/write-env", SetupData, NULL,
              tests_setup, test_write_env, tests_teardown);

  return g_test_run ();
}
